<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Coordinated Universal Time">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="vm001"><DocLocation><![CDATA[C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Driver1]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Driver1]]></DName>
<Res><![CDATA[Res8]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Test1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Test1" started.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:08]]></Time>
<TimeTick>1648548788</TimeTick>
<NodeArgs eType="Transaction" icon="4" nRep="7" nType="Start Transaction" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Test1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (17): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).Close&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:18]]></Time>
<TimeTick>1648548798</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="16" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (17): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).Close&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:26]]></Time>
<TimeTick>1648548806</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="16" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (18): &quot;If WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).Exist(10) Then&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:27]]></Time>
<TimeTick>1648548807</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="17" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[CloseApp]]></Obj>
<Details ><![CDATA[Closeapp unSuccessful]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:29]]></Time>
<TimeTick>1648548809</TimeTick>
<NodeArgs eType="User" icon="6" nRep="11" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="-1" >
<Disp><![CDATA[CloseApp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (29): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfTabStrip(&quot;WpfTabStrip&quot;).Select &quot;SEARCH ORDER&quot;&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:36]]></Time>
<TimeTick>1648548816</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="28" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (29): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfTabStrip(&quot;WpfTabStrip&quot;).Select &quot;SEARCH ORDER&quot;&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:40]]></Time>
<TimeTick>1648548820</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="28" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (29): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfTabStrip(&quot;WpfTabStrip&quot;).Select &quot;SEARCH ORDER&quot;&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:41]]></Time>
<TimeTick>1648548821</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="14" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="28" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (30): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfRadioButton(&quot;byNumberRadio&quot;).Set&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:43]]></Time>
<TimeTick>1648548823</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="15" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="29" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (31): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfEdit(&quot;byNumberWatermark&quot;).Set &quot;8&quot;&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:46]]></Time>
<TimeTick>1648548826</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="16" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="30" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (32): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfButton(&quot;SEARCH&quot;).Click&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:47]]></Time>
<TimeTick>1648548827</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="17" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="31" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (17): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).Close&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:50]]></Time>
<TimeTick>1648548830</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="18" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="16" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (18): &quot;If WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).Exist(10) Then&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:52]]></Time>
<TimeTick>1648548832</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="19" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="17" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[CloseApp]]></Obj>
<Details ><![CDATA[Closeapp unSuccessful]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:53]]></Time>
<TimeTick>1648548833</TimeTick>
<NodeArgs eType="User" icon="6" nRep="20" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="-1" >
<Disp><![CDATA[CloseApp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (29): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfTabStrip(&quot;WpfTabStrip&quot;).Select &quot;SEARCH ORDER&quot;&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:13:59]]></Time>
<TimeTick>1648548839</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="21" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="28" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (30): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfRadioButton(&quot;byNumberRadio&quot;).Set&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:14:01]]></Time>
<TimeTick>1648548841</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="22" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="29" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (31): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfEdit(&quot;byNumberWatermark&quot;).Set &quot;8&quot;&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:14:03]]></Time>
<TimeTick>1648548843</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="23" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="30" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (32): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfButton(&quot;SEARCH&quot;).Click&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:14:04]]></Time>
<TimeTick>1648548844</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="24" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="31" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (38): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfComboBox(&quot;numOfTicketsCombo&quot;).Select &quot;7&quot;&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:14:06]]></Time>
<TimeTick>1648548846</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="25" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="37" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (40): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfButton(&quot;updateBtn&quot;).Click&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:14:08]]></Time>
<TimeTick>1648548848</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="26" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="39" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (17): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).Close&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:14:11]]></Time>
<TimeTick>1648548851</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="27" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="16" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;Micro Focus MyFlight Sample&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl<BR/>Line (18): &quot;If WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).Exist(10) Then&quot;.]]></Details>
<Time><![CDATA[3/29/2022 - 10:14:13]]></Time>
<TimeTick>1648548853</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="28" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="17" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[CloseApp]]></Obj>
<Details ><![CDATA[Closeapp unSuccessful]]></Details>
<Time><![CDATA[3/29/2022 - 10:14:14]]></Time>
<TimeTick>1648548854</TimeTick>
<NodeArgs eType="User" icon="6" nRep="29" status="Failed" Source="C:\Users\sfjbs\Documents\KeywordDrivenFramework\Driver\Library2.qfl" SourceLine="-1" >
<Disp><![CDATA[CloseApp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Test1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Test1" ended with "Fail" status (Total Duration: 65.8389 sec).]]></Details>
<Time><![CDATA[3/29/2022 - 10:14:14]]></Time>
<TimeTick>1648548854</TimeTick>
<NodeArgs eType="Transaction" icon="7" nRep="30" status="Warning" nType="End Transaction" Source="Action1" SourceLine="62" >
<Disp><![CDATA[Test1]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="3/29/2022 - 10:13:08" eTime="3/29/2022 - 10:14:14" passed="0" failed="22" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T28">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="3/29/2022 - 10:14:14" eTime="3/29/2022 - 10:14:14" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="32" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T29">
<AName><![CDATA[Action3]]></AName>
<Summary sTime="3/29/2022 - 10:14:15" eTime="3/29/2022 - 10:14:15" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="34" >
<Disp><![CDATA[Action3 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="3/29/2022 - 10:13:05" eTime="3/29/2022 - 10:14:15" passed="0" failed="22" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Driver1 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>