<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Coordinated Universal Time">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="vm001"><DocLocation><![CDATA[C:\Users\sfjbs\Documents\DataDrivenFramework\Driver\Driver1]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Driver1]]></DName>
<Res><![CDATA[Res33]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Test1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Test1" started.]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:15]]></Time>
<TimeTick>1648631955</TimeTick>
<NodeArgs eType="Transaction" icon="4" nRep="7" nType="Start Transaction" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Test1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:21]]></Time>
<TimeTick>1648631961</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:21]]></Time>
<TimeTick>1648631961</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:22]]></Time>
<TimeTick>1648631962</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:22]]></Time>
<TimeTick>1648631962</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:22]]></Time>
<TimeTick>1648631962</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:22]]></Time>
<TimeTick>1648631962</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:23]]></Time>
<TimeTick>1648631963</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="22" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:23]]></Time>
<TimeTick>1648631963</TimeTick>
<NodeArgs eType="User" icon="9" nRep="23" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:24]]></Time>
<TimeTick>1648631964</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:24]]></Time>
<TimeTick>1648631964</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:34]]></Time>
<TimeTick>1648631974</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="28" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[Closeapp]]></Obj>
<Details ><![CDATA[Closeapp unSuccessful]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:34]]></Time>
<TimeTick>1648631974</TimeTick>
<NodeArgs eType="User" icon="9" nRep="29" status="Passed" >
<Disp><![CDATA[Closeapp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:59]]></Time>
<TimeTick>1648631999</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[3/30/2022 - 9:19:59]]></Time>
<TimeTick>1648631999</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="33" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="32" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:00]]></Time>
<TimeTick>1648632000</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:00]]></Time>
<TimeTick>1648632000</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:00]]></Time>
<TimeTick>1648632000</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="41" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:00]]></Time>
<TimeTick>1648632000</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:00]]></Time>
<TimeTick>1648632000</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="44" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="38" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:00]]></Time>
<TimeTick>1648632000</TimeTick>
<NodeArgs eType="User" icon="9" nRep="45" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:02]]></Time>
<TimeTick>1648632002</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:02]]></Time>
<TimeTick>1648632002</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="48" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:02]]></Time>
<TimeTick>1648632002</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="50" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["4"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:02]]></Time>
<TimeTick>1648632002</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="52" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:03]]></Time>
<TimeTick>1648632003</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="54" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:03]]></Time>
<TimeTick>1648632003</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:03]]></Time>
<TimeTick>1648632003</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="58" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:03]]></Time>
<TimeTick>1648632003</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="60" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:04]]></Time>
<TimeTick>1648632004</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="62" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:04]]></Time>
<TimeTick>1648632004</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="64" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:04]]></Time>
<TimeTick>1648632004</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="66" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:04]]></Time>
<TimeTick>1648632004</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="68" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:04]]></Time>
<TimeTick>1648632004</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="70" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:04]]></Time>
<TimeTick>1648632004</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="72" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:04]]></Time>
<TimeTick>1648632004</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="74" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:04]]></Time>
<TimeTick>1648632004</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="76" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:05]]></Time>
<TimeTick>1648632005</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="78" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:05]]></Time>
<TimeTick>1648632005</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="80" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:05]]></Time>
<TimeTick>1648632005</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="82" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:05]]></Time>
<TimeTick>1648632005</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="84" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:05]]></Time>
<TimeTick>1648632005</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="86" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:05]]></Time>
<TimeTick>1648632005</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="88" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:05]]></Time>
<TimeTick>1648632005</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="90" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:05]]></Time>
<TimeTick>1648632005</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="92" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:05]]></Time>
<TimeTick>1648632005</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="94" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:06]]></Time>
<TimeTick>1648632006</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="96" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:07]]></Time>
<TimeTick>1648632007</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="98" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:17]]></Time>
<TimeTick>1648632017</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="100" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="47" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[Closeapp]]></Obj>
<Details ><![CDATA[Closeapp unSuccessful]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:18]]></Time>
<TimeTick>1648632018</TimeTick>
<NodeArgs eType="User" icon="9" nRep="101" status="Passed" >
<Disp><![CDATA[Closeapp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Test1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Test1" ended with "Pass" status (Total Duration: 63.5972 sec).]]></Details>
<Time><![CDATA[3/30/2022 - 9:20:18]]></Time>
<TimeTick>1648632018</TimeTick>
<NodeArgs eType="Transaction" icon="12" nRep="102" nType="End Transaction" Source="Action1" SourceLine="78" >
<Disp><![CDATA[Test1]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="3/30/2022 - 9:19:15" eTime="3/30/2022 - 9:20:18" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T55">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="3/30/2022 - 9:20:18" eTime="3/30/2022 - 9:20:18" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="104" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T56">
<AName><![CDATA[Action3]]></AName>
<Summary sTime="3/30/2022 - 9:20:19" eTime="3/30/2022 - 9:20:19" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="106" >
<Disp><![CDATA[Action3 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T57">
<AName><![CDATA[Action4]]></AName>
<Summary sTime="3/30/2022 - 9:20:19" eTime="3/30/2022 - 9:20:19" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="108" >
<Disp><![CDATA[Action4 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="3/30/2022 - 9:19:12" eTime="3/30/2022 - 9:20:19" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Driver1 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>